services:
  crawler:
    image: 'tmvdl/fatec_yeb_db:crawler'
    build: ./src/crawler
    ports:
      - 5678:5678
    volumes:
      - ./src/crawler:/app
    depends_on:
      - redis

  redis:
    image: 'tmvdl/fatec_yeb_db:redis'
    build: ./src/redis
    ports:
      - 6379:6379
      - 3000:3000
    volumes:
      - .data/redis:/data
