name: Publish to AWS Lightsail

on:
  schedule:
    - cron: '0 20 * * *' # Runs daily at 8 PM UTC
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        run: echo "${{ secrets.AWS_SSH_KEY }}" > ~/fatec-yeb-db.pem

      - name: Set permissions for SSH key
        run: chmod 400 ~/fatec-yeb-db.pem

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H "${{ secrets.AWS_SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to AWS Lightsail
        run: ssh -i ~/fatec-yeb-db.pem "${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_SSH_HOST }}" 'cd ~/fatec-yeb-db/ && git checkout && bash ./env/docker.down.sh && bash ./env/docker.up.sh && bash ./env/npm.migrate.sh'
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          AWS_SSH_USER: ${{ secrets.AWS_SSH_USER }}
          AWS_SSH_HOST: ${{ secrets.AWS_SSH_HOST }}

      - name: Remove SSH key
        run: rm ~/fatec-yeb-db.pem
